#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("reto8.Resource", IsApplication=true)]

namespace reto8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int buttonAddNick = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int buttonAddToDo = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int buttonLoginUser = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int buttonSearch = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int buttonSearchNick = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int checkNick = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int checkToDoItem = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int listViewNick = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int listViewNicks = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int listViewToDo = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int menu_refresh = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int textNewCost = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int textNewDescription = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int textNewLocation = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int textNewSKU = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int textNewToDo = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int textSearch = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int textSearchDescription = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int textViewSubTitle = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Nick = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_To_Do = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Row_List_Nick = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_To_Do = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int add_item = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int addcost_textbox_hint = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int adddescription_textbox_hint = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int addlocation_textbox_hint = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int addsku_textbox_hint = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int login_button_text = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int registered_items = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int search_button_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int search_item = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int search_textbox_hint = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int searchdescription_textbox_hint = 2130968591;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
